@startuml
left to right direction

actor "Usuario no logeado" as UNL
actor "Usuario logeado" as UL
actor Administrador as A

rectangle Sistema {
    usecase "Registrarse" as UC1
    usecase "Iniciar sesión" as UC2
    usecase "Editar perfil" as UC3
    usecase "Crear entrenos" as UC4
    usecase "Seleccionar entreno" as UC5
    usecase "Guardar entreno" as UC6
    usecase "Compartir entreno" as UC7
    usecase "Reaccionar a entrenos" as UC8
    usecase "Ver dashboard" as UC9
    usecase "Gestionar usuarios" as UC10
}

UNL --> UC1
UNL --> UC2
UNL --> UC9

UL <|-- UNL
UL --> UC3
UL --> UC4
UL --> UC5
UL --> UC6
UL --> UC7
UL --> UC8

A <|-- UL
A --> UC10
@enduml
